from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 580)
        Dialog.setMinimumSize(QtCore.QSize(580, 580))
        Dialog.setMaximumSize(QtCore.QSize(580, 580))
        # 采集照片
        self.photo_pb = QtWidgets.QPushButton(Dialog)
        self.photo_pb.setGeometry(QtCore.QRect(210, 140, 151, 41))
        self.photo_pb.setStyleSheet("font: 14pt \"华文行楷\";")
        self.photo_pb.setObjectName("photo_pb")
        # 操作指南
        self.clear_pb = QtWidgets.QPushButton(Dialog)
        self.clear_pb.setGeometry(QtCore.QRect(210, 190, 151, 41))
        self.clear_pb.setStyleSheet("font: 14pt \"华文行楷\";")
        self.clear_pb.setObjectName("clear_pb")
        # 总采集数量：
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(160, 240, 241, 41))
        self.label_1.setStyleSheet("font: 10pt \"Adobe Arabic\";")
        self.label_1.setObjectName("label_1")
        #
        self.photo_num = QtWidgets.QLabel(Dialog)
        self.photo_num.setGeometry(QtCore.QRect(360, 240, 21, 41))
        self.photo_num.setText("")
        self.photo_num.setObjectName("photo_num")
        #
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 270, 301, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)

        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 20, 121, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "采集界面"))
        self.photo_pb.setText(_translate("Dialog", "开始"))
        self.clear_pb.setText(_translate("Dialog", "操作提示"))
        self.label_1.setText(_translate("Dialog", "总采集照片数量："))
        self.label_10.setText(_translate("Dialog", "0"))
        self.label_6.setText(_translate("Dialog", "  Two"))
        self.label_11.setText(_translate("Dialog", "0"))
        self.label_8.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "0"))
        self.label_7.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "Good"))
        self.label_2.setText(_translate("Dialog", "No"))
        self.label_3.setText(_translate("Dialog", "One"))
        self.label_4.setText(_translate("Dialog", "  Three"))
        self.label.setText(_translate("Dialog", "Fist"))
        self.label_12.setText(_translate("Dialog", "0"))
